import java.util.*;
class A
{
static void cal()throws ArithmeticException
{
System.out.println(10/0);
}
public static void main(String args[])
{
try
{
cal();
}
catch(Exception e)
{
System.out.println("Exception handle in main");
}
}
}
